# Generated by Skyramp v1.3.30 on 2026-06-29 19:39:45.326701166 +0000 UTC m=+294.706280944
# Command: skyramp generate contract rest http://localhost:7860/api/v1/validate/flow \
# 		--api-schema http://localhost:7860/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output validate_flow_cycle_detection_contract_test.py \
# 		--output-dir /home/runner/work/langflow/langflow/src/backend/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"nodes":[{"id":"node-x"},{"id":"node-y"}],"edges":[{"source":"node-x","target":"node-y"},{"source":"node-y","target":"node-x"}]} \
# 		--response-data {"node_count":2,"edge_count":2,"root_nodes":[],"leaf_nodes":[],"isolated_nodes":[],"has_cycles":true,"is_connected":true} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:7860")

# contract test for /api/v1/validate/flow POST
def test_flow_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flow_POST_request_body = r'''{
        "edges": [
            {
                "source": "node-x",
                "target": "node-y"
            },
            {
                "source": "node-y",
                "target": "node-x"
            }
        ],
        "nodes": [
            {
                "id": "node-x"
            },
            {
                "id": "node-y"
            }
        ]
    }'''

    # Expected Response Body
    expected_flow_POST_response_body = r'''{
        "edge_count": 2,
        "has_cycles": true,
        "is_connected": true,
        "isolated_nodes": [],
        "leaf_nodes": [],
        "node_count": 2,
        "root_nodes": []
    }'''

    # Execute Request
    flow_POST_response = client.send_request(
        url=URL,
        path="/api/v1/validate/flow",
        method="POST",
        body=flow_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert flow_POST_response.status_code == 200
    assert skyramp.get_response_value(flow_POST_response, "node_count") == 2
    assert skyramp.get_response_value(flow_POST_response, "edge_count") == 2
    assert skyramp.get_response_value(flow_POST_response, "has_cycles") == True
    assert skyramp.get_response_value(flow_POST_response, "is_connected") == True
    assert skyramp.get_response_value(flow_POST_response, "root_nodes.0") is None
    assert skyramp.get_response_value(flow_POST_response, "leaf_nodes.0") is None
    assert skyramp.get_response_value(flow_POST_response, "isolated_nodes.0") is None
    assert skyramp.check_schema(flow_POST_response, expected_flow_POST_response_body)
    assert skyramp.get_response_value(flow_POST_response, "edge_count") is not None
    assert skyramp.get_response_value(flow_POST_response, "has_cycles") is not None
    assert skyramp.get_response_value(flow_POST_response, "is_connected") is not None


if __name__ == "__main__":
    test_flow_post()
