# Generated by Skyramp v1.3.30 on 2026-06-29 19:39:50.093071397 +0000 UTC m=+299.472651165
# Command: skyramp generate contract rest http://localhost:7860/api/v1/validate/flow \
# 		--api-schema http://localhost:7860/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output validate_flow_disconnected_contract_test.py \
# 		--output-dir /home/runner/work/langflow/langflow/src/backend/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"nodes":[{"id":"n1"},{"id":"n2"},{"id":"n3"}],"edges":[{"source":"n1","target":"n2"}]} \
# 		--response-data {"node_count":3,"edge_count":1,"root_nodes":["n1","n3"],"leaf_nodes":["n2","n3"],"isolated_nodes":["n3"],"has_cycles":false,"is_connected":false} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:7860")

# contract test for /api/v1/validate/flow POST
def test_flow_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flow_POST_request_body = r'''{
        "edges": [
            {
                "source": "n1",
                "target": "n2"
            }
        ],
        "nodes": [
            {
                "id": "n1"
            },
            {
                "id": "n2"
            },
            {
                "id": "n3"
            }
        ]
    }'''

    # Expected Response Body
    expected_flow_POST_response_body = r'''{
        "edge_count": 1,
        "has_cycles": false,
        "is_connected": false,
        "isolated_nodes": [
            "n3"
        ],
        "leaf_nodes": [
            "n2",
            "n3"
        ],
        "node_count": 3,
        "root_nodes": [
            "n1",
            "n3"
        ]
    }'''

    # Execute Request
    flow_POST_response = client.send_request(
        url=URL,
        path="/api/v1/validate/flow",
        method="POST",
        body=flow_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert flow_POST_response.status_code == 200
    assert skyramp.get_response_value(flow_POST_response, "node_count") == 3
    assert skyramp.get_response_value(flow_POST_response, "edge_count") == 1
    assert skyramp.get_response_value(flow_POST_response, "has_cycles") == False
    assert skyramp.get_response_value(flow_POST_response, "is_connected") == False
    assert skyramp.get_response_value(flow_POST_response, "root_nodes.0") == "n1"
    assert skyramp.get_response_value(flow_POST_response, "root_nodes.1") == "n3"
    assert skyramp.get_response_value(flow_POST_response, "root_nodes.2") is None
    assert skyramp.get_response_value(flow_POST_response, "leaf_nodes.0") == "n2"
    assert skyramp.get_response_value(flow_POST_response, "leaf_nodes.1") == "n3"
    assert skyramp.get_response_value(flow_POST_response, "leaf_nodes.2") is None
    assert skyramp.get_response_value(flow_POST_response, "isolated_nodes.0") == "n3"
    assert skyramp.get_response_value(flow_POST_response, "isolated_nodes.1") is None
    assert skyramp.check_schema(flow_POST_response, expected_flow_POST_response_body)
    assert skyramp.get_response_value(flow_POST_response, "edge_count") is not None
    assert skyramp.get_response_value(flow_POST_response, "has_cycles") is not None
    assert skyramp.get_response_value(flow_POST_response, "is_connected") is not None


if __name__ == "__main__":
    test_flow_post()
